#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.1.1/collabtive-211.zip"
URL="http://downloads.sourceforge.net/project/collabtive/collabtive/$VERSION"

dl $URL /usr/local/src

