#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="0.7.6/collabtive076.zip"
URL="http://sourceforge.net/projects/collabtive/files/collabtive/$VERSION"

dl $URL /usr/local/src

