#!/bin/sh -ex

DB_NAME=collabtive
DB_USER=collabtive
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/collabtive

# unpack and set permissions
mkdir -p $WEBROOT
unzip $SRC/collabtive*.zip -d $WEBROOT
rm $SRC/collabtive*.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/files
chown -R www-data:www-data $WEBROOT/templates_c
chown -R www-data:www-data $WEBROOT/config/standard/config.php
chmod 640 $WEBROOT/config/standard/config.php

# configure apache
a2dissite 000-default
a2ensite collabtive
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start


# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
URL="http://127.0.0.1/install.php?locale=en&"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL "${URL}action=step2" --data "db_driver=mysql&db_host=localhost&db_name=$DB_NAME&db_user=$DB_USER&db_pass=$DB_PASS"
sleep 5
$CURL "${URL}action=step3" --data "name=$ADMIN_NAME&pass=$ADMIN_PASS"

rm $WEBROOT/install*
rm $WEBROOT/update.php
rm -f /tmp/cookie

# set default mail settings and subtitle
$MYSQL_BATCH --execute " \
    UPDATE $DB_NAME.settings SET settingsValue=\"$ADMIN_MAIL\" where settingsKey=\"mailfrom\"; \
    UPDATE $DB_NAME.settings SET settingsValue=\"Collabtive Admin\" where settingsKey=\"mailfromname\"; \
    UPDATE $DB_NAME.settings SET settingsValue=\"smtp\" where settingsKey=\"mailmethod\"; \
    UPDATE $DB_NAME.settings SET settingsValue=\"localhost\" WHERE settingsKey=\"mailhost\"; \
    UPDATE $DB_NAME.settings SET settingsValue=\"TurnKey Collabtive\" WHERE settingsKey=\"subtitle\"; \
"
# tweak footer
HTML="<div id='turnkey-credit' style='padding-top:20px;text-align:center;font-size:11px;color:#6AB0C5;'><a style='color:#6AB0C5;' href='https://www.turnkeylinux.org/collabtive'>Collabtive Appliance</a> - Powered by <a style='color:#6AB0C5;' href='https://www.turnkeylinux.org'>TurnKey Linux</a></div>"

sed -i "s|</body>|$HTML\n</body>|" $WEBROOT/templates/standard/footer.tpl

sed -i "s|{/if}|{/if}\n$HTML|" $WEBROOT/templates/standard/login.tpl

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop
