#!/bin/sh -ex

DB_NAME=collabtive
DB_USER=collabtive
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/collabtive

# unpack and set permissions
mkdir -p $WEBROOT
unzip $SRC/collabtive*.zip -d $WEBROOT
rm $SRC/collabtive*.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/files
chown -R www-data:www-data $WEBROOT/templates_c
chown -R www-data:www-data $WEBROOT/config/standard/config.php
chmod 640 $WEBROOT/config/standard/config.php

# bugfix: get rid of buggy language
rm -rf $WEBROOT/language/et

# configure apache
a2dissite default
a2ensite collabtive
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

