#!/bin/bash -e
# regenerate collabtive mysql password

. /etc/default/inithooks

CONF=/var/www/collabtive/config/standard/config.php
PASSWORD=$(mcookie)
sed -i "s|db_pass.*|db_pass = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=collabtive --pass="$PASSWORD"

