#!/bin/bash -e
# set collabtive admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/collabtive.py --pass="$APP_PASS" --email="$APP_EMAIL"

